### ISSUE TITLE
Error on preflight when using bookmark

### ISSUE THREAD

**Issue by pstuifzand** [cleverdevil/indiepaper#1]
I get an error in Chrome "Failed to load https://indiepaper.io/: Response for preflight is invalid (redirect)"

It seems the redirect doesn't work right with the OPTIONS request.

**Comment by cleverdevil** [comment]
Fixed in https://github.com/cleverdevil/indiepaper/commit/29c169ee22bc6e52b974ff8b44b11dbd341d9735
