### ISSUE TITLE
Look for mf2 first, use Mercury as a fallback

### ISSUE THREAD

**Issue by aaronpk** [cleverdevil/indiepaper#2]
If the page has mf2, that is likely to be much better data than what Mercury finds. Indiepaper should first check if it finds an article via mf2, and if it doesn't, then can use Mercury to extract what it can.

**Comment by cleverdevil** [comment]
Great suggestion. I am debating either including mf2py as a dependency, or just using [https://python.microformats.io](https://python.microformats.io) as a web service like I do with Mercury, so I don't have to worry about keeping it up to date.

I will likely want to take the output from mf2py and strip out everything but the basics. Any directional feedback is, of course, welcome!

[](https://brid.gy/publish/github)

(Originally published at: https://cleverdevil.io/2018/great-suggestion-i-am-debating-either-including-mf2py-as-a)

**Comment by cleverdevil** [comment]
Done in https://github.com/cleverdevil/indiepaper/commit/6b7162cbb94387e9da2b7a2e5deaeba9602d3f96
