### ISSUE TITLE
add h-app markup

### ISSUE THREAD

**Issue by aaronpk** [cleverdevil/indiepaper#4]
The IndieAuth prompt will look better if it can show the application name and icon. This is just a matter of adding a bit of Microformats to your application's home page. https://indieweb.org/h-x-app

![](https://media.aaronpk.com/Screen-Shot-2018-07-07-20-24-22-uPxNqPIViE.jpg)

**Comment by cleverdevil** [comment]
I think I have done this properly in https://github.com/cleverdevil/indiepaper-website/commit/3a290fc6253d758d50be0859b1d6c1ddc0d6ddc5

Give it a shot and let me know if it works! If it does, I’ll close the issue.
