### ISSUE TITLE
Login loop

### ISSUE THREAD

**Issue by dixonge** [cleverdevil/indiepaper#6]
I successfully logged in using IndieAuth off of my site, but I am simply taken back to the login page without any indication as to whether or not the login was successful, and no errors. The url indicates success, but nothing else. [Here is where I end up](https://www.indiepaper.io/indieauth.html?success=true)

**Comment by dixonge** [comment]
If I go back to the main site and enter an endpoint and create a 'read later' bookmark, I get a 'saved' popup with no indication of where, exactly, I might go find this saved content to read later. I get no posts or pages or anything on my site, so where has it been saved to?

**Comment by cleverdevil** [comment]
Can you give me a bit more information?

* What URL are you entering into the form for IndieAuth?
* What CMS or service are you using for that domain?
* Are you able to successfully IndieAuth using that domain with other services, like [Quill](https://quill.p3k.io)?
* When you create the bookmarklet manually, are you entering a Micropub endpoint and a valid Authorization token? Have you verified that the token works?

Thanks!

**Comment by dixonge** [comment]
1 - https://glenn.thedixons.net
2 - WordPress
3 - yes
4 - where would I get this Authorization token? <<---- This is probably my problem...

**Comment by cleverdevil** [comment]
Thanks for the information!

I have verified that Indiepaper's IndieAuth flow works with the latest WordPress. Are you up-to-date with both your WordPress version and the Indieweb plugins, including the IndieAuth support?

I'm not familiar enough with the WordPress IndieAuth support to know if you can manually generate a token, but if you wanted to get a token to test with you could log in to Quill and then copy the information from [the settings page](https://quill.p3k.io/settings).

All that said, I am not sure you'll actually want to use Indiepaper to save articles to your personal website, as that will just publish them as articles on your site. I usually recommend people either set up a separate site for reading, or use a service like [Aperture](https://aperture.p3k.io), which is designed for reading, and supports Indiepaper really nicely by logging in with "https://aperture.p3k.io" to save articles to your own "channels."

**Comment by dixonge** [comment]
My WordPress and all plugins were first installed two days ago, so yes, they should be up to date.

I like keeping things out of the silos, and I am still in the process of investigating Indie readers (like Aperture) so I'll probably just go that direction. But thanks for the tip - in retrospect, publishing things to read later to my site, even temporarily, would probably not be good in the long run. Not counting books :)
