### ISSUE TITLE
Bookmarklets do not function

### ISSUE THREAD

**Issue by dixonge** [cleverdevil/indiepaper#8]
I've tried both the default and a custom-created bookmarklet (using my own access token and endpoint). Neither work. Clicking on the button does nothing. No alerts, no errors.

I have several other bookmarklets tied to my WordPress site which work just fine and open various posting windoes. IndiePaper doesn't seem to be doing anything.

**Comment by cleverdevil** [comment]
Do you see any errors in your JavaScript console in your browser? Which web browser are you using? On what OS? What version of the browser? Do you see any errors in your WordPress?

**Comment by cleverdevil** [comment]
Also, I just pushed a change to production that could potentially solve the problem, but it requires you to go through the full IndieAuth procedure again, which will generate a new "token" and then new bookmarklets for you to try.

**Comment by dixonge** [comment]
The good news is that this does, in fact, work now.

2 remaining issues (possibly feature enhancements):

1 - long delay before the 'saved' button comes up with no indication that anything is happening
2 - The entire page is going into my main default post category (articles) instead of my bookmarks/link category. Can I tweak the code in the bookmarklet and adjust that? (WordPress)

**Comment by cleverdevil** [comment]
Great I am glad it seems to be working!

Yes, the bookmarklet could use some improvement to make it clearer that things are being saved. I'll work on this at some point.

That's a good question on WordPress. I don't know enough about the WordPress micropub support to know for sure.

Hey, @dshanske, the fix I mention above was to request "create update" scope in the IndieAuth exchange, in addition to the "save" scope I was requesting before. It'd be great if the WordPress micropub endpoint could know that Indiepaper is requesting the "save" scope, and then do something smarter with the content sent over. Ideas?

**Comment by cleverdevil** [comment]
In the indieweb WordPress IRC, I mentioned this, and @aaronpk pointed me to this issue:

https://github.com/indieweb/wordpress-indieauth/issues/28

A change like this in WordPress' IndieAuth/Micropub support would be the best course of action.
